branch-defaults:
  default:
    environment: udagram-env
  master:
    environment: udagram-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
